#!/usr/bin/env python
# coding: utf-8


#import required modules
import gzip
import pandas as pd
import time


#open data and create DF
with gzip.open('green_tripdata_2019-01.csv.gz', 'rt') as f:
    df = pd.read_csv(f)


#check data structure
df.head()


#change columns to datetime
df.lpep_pickup_datetime = pd.to_datetime(df.lpep_pickup_datetime)
df.lpep_dropoff_datetime = pd.to_datetime(df.lpep_dropoff_datetime)



#import create_engine
from sqlalchemy import create_engine


#define engine
engine = create_engine('postgresql://root:root@localhost:5432/ny_taxi')


#connect engine to port
engine.connect()


#see data structure of table created in pgcli
print(pd.io.sql.get_schema(df, name = 'green_taxi_data_homework',con = engine))


#define as iterator
f = gzip.open('green_tripdata_2019-01.csv.gz', 'rt') 
df_iter = pd.read_csv(f, iterator = True,chunksize = 100000)



df = next(df_iter)


#create green_taxi_data_homework table
while True:
    t_start = time.time()
    df = next(df_iter)
    df.lpep_pickup_datetime = pd.to_datetime(df.lpep_pickup_datetime)
    df.lpep_dropoff_datetime = pd.to_datetime(df.lpep_dropoff_datetime)
    df.to_sql('green_taxi_data_homework', con=engine, if_exists = 'append')
    print('inserted another chunk...')
    t_end = time.time()
    print('inserted another chunk..., took %.3f second' % (t_end - t_start))



# doing the same for zone data
import gzip
import pandas as pd
import time




new_df = pd.read_csv('taxi_zone_lookup.csv')



#create taxi_zone_lookup table
df.to_sql('taxi_zone_lookup', con=engine, if_exists = 'append')

